stages:
  - build

build:
  stage: build
  image: node:18.17.1
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-9 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install # install dependencies
    - pnpm run docs:build
    - mv .vitepress/dist public
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
  artifacts:
    paths:
      - public
  # only:
  #   - main
pages:
  stage: deploy
  image: node:18.17.1
  script:
    - echo 'Deploying'
  dependencies:
    - build
  artifacts:
    paths:
      - public
  # only:
  #   - masters
  # rules:
  #   - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  #     when: always
  #   - if: $CI_COMMIT_TAG
  #     when: always
  #   - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_TAG
  #     when: never
  #   - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_TAG
  #     when: never
  #   - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && !$CI_COMMIT_TAG
  #     when: never
  #   - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && !$CI_COMMIT_TAG
  #     when: always